### ISSUE TITLE
bluebird Dependency

### ISSUE THREAD

**Issue by kayaelle** [brianloveswords/streamsql#15]
Heya- when installing streamsql, I get this error:

No compatible version found: bluebird@'^1.0.8'
Looks like bluebird is at 1.2.0. 

Thanks

**Comment by brianloveswords** [comment]
It works for me, what version of `node` and `npm` are you using? I think it could be the `^` causing it (http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/)

I can also change it in package.json, since after 1.0.0 my understanding is that tildes and carets are semantically equivalent.

**Comment by brianloveswords** [comment]
Okay, I changed it in package.json to `~1.2.0` so it should be compatible with older versions of npm.

**Comment by brianloveswords** [comment]
Published `0.6.0`

**Comment by kayaelle** [comment]
Yeah - it probably was my npm version.

node: 0.10.15
npm: 1.3.5 

updated to 1.4.6 and installed fine without your update to package.

Thanks!
